//
//  CLDDrawables.h
//  MEOCloudSDK
//
//  Created by Hugo Sousa on 14/08/14.
//  Copyright (c) 2014 SAPO. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface CLDDrawables : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginNavigationButtonTargets;

// Generated Images
+ (UIImage*)imageOfLoginNavigationButtonWithRotation: (CGFloat)rotation;

@end
