//
//  CLDDrawables.m
//  MEOCloudSDK
//
//  Created by Hugo Sousa on 14/08/14.
//  Copyright (c) 2014 SAPO. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "CLDDrawables.h"


@implementation CLDDrawables

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawLoginNavigationButtonWithRotation: (CGFloat)rotation;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //// Bezier Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 5.91, 10.51);
    CGContextRotateCTM(context, -rotation * M_PI / 180);
    
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(4.42, -9.24)];
    [bezierPath addLineToPoint: CGPointMake(5.35, -8.22)];
    [bezierPath addCurveToPoint: CGPointMake(-3.36, -0) controlPoint1: CGPointMake(5.35, -8.22) controlPoint2: CGPointMake(-0.91, -2.21)];
    [bezierPath addCurveToPoint: CGPointMake(5.36, 8.2) controlPoint1: CGPointMake(-0.92, 2.19) controlPoint2: CGPointMake(5.36, 8.2)];
    [bezierPath addLineToPoint: CGPointMake(4.42, 9.24)];
    [bezierPath addCurveToPoint: CGPointMake(-5.36, -0) controlPoint1: CGPointMake(4.42, 9.24) controlPoint2: CGPointMake(-5.49, 0.14)];
    [bezierPath addCurveToPoint: CGPointMake(4.42, -9.24) controlPoint1: CGPointMake(-5.48, -0.14) controlPoint2: CGPointMake(4.42, -9.24)];
    [bezierPath closePath];
    [UIColor.grayColor setFill];
    [bezierPath fill];
    
    CGContextRestoreGState(context);
}

#pragma mark Generated Images

+ (UIImage*)imageOfLoginNavigationButtonWithRotation: (CGFloat)rotation;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(12, 21), NO, 0.0f);
    [CLDDrawables drawLoginNavigationButtonWithRotation: rotation];
    UIImage* imageOfLoginNavigationButton = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();
    
    return imageOfLoginNavigationButton;
}

@end
